<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QPay_Web_Data\QPay.DAL.csproj" />
    <ProjectReference Include="..\QPAY_Web_Domain\QPay.UI.csproj" />
    <ProjectReference Include="..\QPAY_Web_Service\QPay.BAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GST_Certificate\" />
    <Folder Include="LUT_Certificate\" />
    <Folder Include="SEZ_Certificate\" />
    <Folder Include="ReimbursementPolicyUploads\" />
    <Folder Include="PayRegister\Processed\" />
    <Folder Include="PayRegister\Unprocessed\" />
  </ItemGroup>

</Project>
