using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QPay.UI.Models;

namespace QPay.BAL.IRepository
{
    public interface IQARepository
    {
        Task<List<CustomerSOPQuestion>> GetCustomerSOPQuestionAnswer();
        Task<CompanyMaster> GetCompanyCode(int user_id);
        Task<List<StateMaster>> GetState();
        Task<List<CityMaster>> GetCity(int state_id);
        Task<List<DesignationMaster>> GetDesignation(string company_code);
        Task<List<FirstMonthPayroll>> GetFirstMonthPayroll(string companyId);
        Task<List<Category>> GetCategory();
        Task<List<Question>> GetQuestion(int categoryId);
        Task<List<Answer1>> GetSOPAnswer1(int QuestionId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer1(Answer1 answer1);
        Task<Answer2> GetSOPAnswer2(int QuestionId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer2(Answer2 answer2);
        Task<Answer3> GetSOPAnswer3(int QuestionId, int ComapnayId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer3(Answer3 answer2);
        Task<Answer6> GetSOPAnswer6(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer6(Answer6 answer6);
        Task<Answer8> GetSOPAnswer8(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer8(Answer8 answer8);
        Task<Answer9> GetSOPAnswer9(int QuestionId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer9(Answer9 answer9);
        Task<Answer10> GetSOPAnswer10(int QuestionId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer10(Answer10 answer10);
        Task<Answer5> GetSOPAnswer5(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer5(Answer5 answer5);
        Task<List<Answer7>> GetSOPAnswer7(int QuestionId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer7(Answer7 answer7);
        Task<Answer13> GetSOPAnswer13(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer13(Answer13 answer13);
        Task<Answer14> GetSOPAnswer14(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer14(Answer14 answer14);
        Task<Answer16> GetSOPAnswer16(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer16(Answer16 answer16);
        Task<Answer17> GetSOPAnswer17(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer17(Answer17 answer17);
        Task<Answer18> GetSOPAnswer18(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer18(Answer18 answer18);
        Task<Answer19> GetSOPAnswer19(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer19(Answer19 answer19);
        Task<Answer21> GetSOPAnswer21(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer21(Answer21 answer21);
        Task<Answer23> GetSOPAnswer23(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer23(Answer23 answer23);
        Task<Answer25> GetSOPAnswer25(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer25(Answer25 answer25);
        Task<Answer28> GetSOPAnswer28(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer28(Answer28 answer28);
        Task<Answer29> GetSOPAnswer29(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer29(Answer29 answer29);
        Task<Answer30> GetSOPAnswer30(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer30(Answer30 answer30);
        Task<Answer32> GetSOPAnswer32(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer32(Answer32 answer32);
        Task<Answer36> GetSOPAnswer36(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer36(Answer36 answer36);
        Task<Answer37> GetSOPAnswer37(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer37(Answer37 answer37);
        Task<Answer38> GetSOPAnswer38(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer38(Answer38 answer38);
        Task<List<Answer12>> GetSOPAnswer12(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer12(List<Answer12> answer12);
        Task<Answer27> GetSOPAnswer27(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer27(Answer27 answer27);
        Task<Answer39> GetSOPAnswer39(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer39(Answer39 answer39);
        Task<List<Marked_Category>> GetmarkedQuestion(int CompanyId, string Createdby);
        Task<Answer4RequestGet> GetSOPAnswer4(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer4(Answer4Request answer4);
        Task<Answer33RequestGet> GetSOPAnswer33(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer33(Answer33Request answer33);
        Task<AnswerResponse> PostSOPAnswer31(IFormFile file, [FromForm] string billApplicable,
            [FromForm] int QuestionId, [FromForm] int CompanyId, [FromForm] string CreatedBy);
        Task<AnswerResponse> PostSOPAnswer31_1([FromForm] string billApplicable,
           [FromForm] int QuestionId, [FromForm] int CompanyId, [FromForm] string CreatedBy);
        Task<Answer31> GetSOPAnswer31(int QuestionId, int CompanyId, string Createdby, string fullUrl);
        Task<Answer11RequestGet> GetSOPAnswer11(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer11(Answer11Request answer11);
        Task<Answer15RequestGet> GetSOPAnswer15(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer15(Answer15Request answer15);
        Task<AnswerResponse> PostSOPAnswer20(Answer20 answer20);
        Task<List<Answer20>> GetSOPAnswer20(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer22(Answer22 answer22);
        Task<List<Answer22>> GetSOPAnswer22(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer24(Answer24 answer24);
        Task<List<Answer24>> GetSOPAnswer24(int QuestionId, int CompanyId, string Createdby);
        Task<List<PermissionwiseCompanyModel>> GetUserWiseCompanyCode(int UserId);
        Task<List<PremiumTracker>> GetPremiumTracker26();
        Task<List<InsuranceCoverageType>> GetCoverageType26();
        Task<List<Policy>> GetGPAPolicy26();
        Task<List<Policy>> GetGTLIPolicy26();
        Task<List<Paycode>> GetDeductionPaycode26();
        Task<List<Paycode>> GetBillingPaycode26();
        Task<List<string>> GetMartialStatus26();
        Task<List<EmployeeType>> GetEmployeeType26();
        Task<List<NewJoinee_Arrear>> GetNewJoinee26();
        Task<List<GroupDetails>> GetAllGroupByCompany(int CompanyId);
        Task<List<InsuranceVertical>> GetInsuranceVertical(int CompanyId);
        Task<List<DesignationMaster>> GetAllDesignationByCompany(int CompanyId);
        Task<List<GMCPolicyCondition>> GetPolicyConditionByCoverageType(int CoverageTypeId);
        Task<List<GMCPolicyNo>> GetPolicyNoByCondition(int CoverageTypeId, int PolicyConditionId);
        Task<AnswerResponse> InsuranceExists(InsuranceAlreadyExists answer26);
        Task<AnswerResponse> InsuranceCreate(InsuranceAdd answer26);
        Task<List<InsurancePolicy>> GetSOPInsurance26(int QuestionId, string Createdby);
        Task<List<Client>> GetClientName26();
        Task<AnswerResponse> PostSOPAnswer35(Answer35 answer35);
        Task<List<Answer35>> GetSOPAnswer35(int QuestionId, string Createdby);
        Task<List<Answer34>> GetSOPAnswer34(int QuestionId, int CompanyId, string Createdby, string fullUrl);
        Task<AnswerResponse> PostSOPAnswer34([FromForm] Answer34 answer34, IFormFile? fileGST = null, IFormFile? fileSEZ = null, IFormFile? fileLUT = null);
        Task<List<Country>> GetCountry();
        Task<List<Currency>> GetCurrency();
        Task<List<Answer40>> GetSOPAnswer40(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer40(Answer40 answer40);
        Task<List<Answer41>> GetSOPAnswer41(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswer41(Answer41 answer41);
        Task<List<Answer42_1>> GetSOPAnswerCompliance42(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswerCompliance42(Answer42_1 answer42_1);
        Task<List<Answer42_2>> GetSOPAnswerMinimumwages42(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswerMinimumwages42(Answer42_2 answer42_2);
        Task<List<Answer42_3>> GetSOPAnswerDesignation42(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswerDesignation42(Answer42_3 answer42_3);
        Task<List<Answer42_4>> GetSOPAnswerCLRA42(int QuestionId, int CompanyId, string Createdby);
        Task<AnswerResponse> PostSOPAnswerCLRA42(Answer42_4 answer42_4);
        Task<AnswerResponse> DeleteSOPAnswer31(int QuestionId, string Createdby);
    }
}
